version: 2.1

jobs:
  onepoint3acres:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install requests 2captcha-python
      - run:
          name: Run 1point3acres signin
          command: |
            python -m onepoint3acres.onepoint3acres

workflows:
  # Allow manual triggers
  manual_trigger:
    jobs:
      - nodeseek:
          context: checkincontext
      - v2ex:
          context: checkincontext
      - onepoint3acres:
          context: checkincontext
